[tool-chain]
solana-version = "2.1.0"
anchor_version = "0.31.1"

[features]
seeds = false
devnet = true

[programs.localnet]
amm_v3 = "6dMXqGZ3ga2dikrYS9ovDXgHGh5RUsb2RTUj6hrQXhk6"

[programs.devnet]
amm_v3 = "6dMXqGZ3ga2dikrYS9ovDXgHGh5RUsb2RTUj6hrQXhk6"

[programs.mainnet]
amm_v3 = "6dMXqGZ3ga2dikrYS9ovDXgHGh5RUsb2RTUj6hrQXhk6"

[registry]
url = "https://github.com/stabbleorg/clmm"

[provider]
cluster = "devnet"
wallet = ".keypair/devnet.json"
