[tool-chain]
solana-version = "2.1.0"
anchor_version = "0.31.1"

[features]
seeds = false

[programs.localnet]
amm_v3 = "6dMXqGZ3ga2dikrYS9ovDXgHGh5RUsb2RTUj6hrQXhk6"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
